In [ ]:
# Data Cleaning

## Objective

# Prepare the dataset for analysis by validating data quality, 
# handling missing values, checking duplicates, and creating analysis-ready fields.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/amazon.csv")

In [2]:
df["OrderDate"].head()

0    2023-01-31
1    2023-12-30
2    2022-05-10
3    2023-07-18
4    2023-02-04
Name: OrderDate, dtype: str

In [3]:
df["OrderDate"].dtype

In [4]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [5]:
df["OrderDate"].dtype

dtype('<M8[us]')

In [6]:
df["Year"] = df["OrderDate"].dt.year

In [7]:
df[["OrderDate", "Year"]].head()

   OrderDate  Year
0 2023-01-31  2023
1 2023-12-30  2023
2 2022-05-10  2022
3 2023-07-18  2023
4 2023-02-04  2023

In [8]:
df["Month"] = df["OrderDate"].dt.month

In [9]:
df[["OrderDate", "Month"]].head()

   OrderDate  Month
0 2023-01-31      1
1 2023-12-30     12
2 2022-05-10      5
3 2023-07-18      7
4 2023-02-04      2

In [10]:
df["MonthName"] = df["OrderDate"].dt.month_name()

In [11]:
df[["OrderDate", "MonthName"]].head()

   OrderDate MonthName
0 2023-01-31   January
1 2023-12-30  December
2 2022-05-10       May
3 2023-07-18      July
4 2023-02-04  February

In [12]:
df["Quarter"] = df["OrderDate"].dt.quarter

In [13]:
df[["OrderDate", "Quarter"]].head()

   OrderDate  Quarter
0 2023-01-31        1
1 2023-12-30        4
2 2022-05-10        2
3 2023-07-18        3
4 2023-02-04        1

In [14]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,PaymentMethod,OrderStatus,City,State,Country,SellerID,Year,Month,MonthName,Quarter
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,Debit Card,Delivered,Washington,DC,India,SELL01967,2023,1,January,1
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,2023,12,December,4
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,Debit Card,Delivered,Austin,TX,United States,SELL00908,2022,5,May,2
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,2023,7,July,3
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,2023,2,February,1

In [15]:
df.to_csv("data/amazon_cleaned.csv", index=False)

In [16]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

df["Year"] = df["OrderDate"].dt.year

df["Month"] = df["OrderDate"].dt.month

df["MonthName"] = df["OrderDate"].dt.month_name()

df["Quarter"] = df["OrderDate"].dt.quarter

df.to_csv("data/amazon_cleaned.csv", index=False)

In [17]:
df[["OrderDate","Year","Month","MonthName","Quarter"]].head()

   OrderDate  Year  Month MonthName  Quarter
0 2023-01-31  2023      1   January        1
1 2023-12-30  2023     12  December        4
2 2022-05-10  2022      5       May        2
3 2023-07-18  2023      7      July        3
4 2023-02-04  2023      2  February        1

In [18]:
df["Year"].value_counts()

Year
2023    20096
2022    20078
2020    20066
2021    19890
2024    19870
Name: count, dtype: int64

In [19]:
df[[
    "Quantity",
    "UnitPrice",
    "Discount",
    "Tax",
    "ShippingCost",
    "TotalAmount"
]].head(10)

   Quantity  UnitPrice  Discount     Tax  ShippingCost  TotalAmount
0         3     106.59      0.00    0.00          0.09       319.86
1         1     251.37      0.05   19.10          1.74       259.64
2         3      35.03      0.10    7.57          5.91       108.06
3         5      33.58      0.15   11.42          5.53       159.66
4         2     515.64      0.25   38.67          9.23       821.36
5         4     449.73      0.00  215.87          2.74      2017.53
6         2     219.81      0.20   28.14         14.97       394.81
7         2     306.51      0.05   29.12          6.24       617.73
8         4     146.09      0.00   46.75          7.03       638.14
9         2     278.21      0.10   60.09          4.88       565.75

In [ ]:
# Conclusion

# The analysis revealed that revenue is concentrated among a small group of high-performing categories, brands, and locations.
# These findings can help prioritize marketing investment and inventory planning.